version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-71-231-180.compute-1.amazonaws.com
            database: d6bd03kmho6s9f
            schema: public
            user: ksxjjpbhajrygy
            password: 62c66379df61396821fe22f3d13759bc44255fcd4c9d48af0ab741b83af5c2cc
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true